clear;
load ('training.mat');
load('validate.mat');
N=size(training,1);
N_V=size(validate,1);
M=3;
W=zeros(M,1);
e=0;
X=Calculate_X(M,training);
X_V=Calculate_X(M,validate);
R=X*(X')/(N-M);
Lamda_Max=max(svd(R));
j=1500;
Mu=(1/Lamda_Max)/j;
[W,OUTPUT]=train(W,e,X,Mu,training,M);
j=1300;
Mu=(1/Lamda_Max)/j;
W=zeros(M,1);
[W,OUTPUTA]=train(W,e,X,Mu,training,M);
j=500;
Mu=(1/Lamda_Max)/j;
W=zeros(M,1);
[W,OUTPUTB]=train(W,e,X,Mu,training,M);
plot(1:N-M,OUTPUT,1:N-M,OUTPUTA,1:N-M,OUTPUTB)
legend('Step size A',' Step Size B',' StepSize Optimal');